### ISSUE TITLE
Application Fails without Error

### ISSUE THREAD

**Issue by MSDP** [realcrowd/hellosign.net#10]
When attempting to use this Library, my application gets to:

HelloSignService.cs
Line 101:             using (var requestStream = await webReq.GetRequestStreamAsync())

Then simply exits without error, I stepped through the entire application and when it gets there it simply closes?

**Comment by MSDP** [comment]
When converting the functions to non-async I was able to get debug information out of it.

+		$exception	{"The remote server returned an error: (400) Bad Request."}	System.Exception {System.Net.WebException}


var requestSignature = new SignatureRequestSendRequest
            {
                Title = "Test",
                Subject = "Subject",
                Message = "Wweeeeeeee",
                TestMode = 1,
                Signers = new List<SignerRequest>
                {
                    new SignerRequest
                    {
                        EmailAddress = "jacob@ms-dp.net",
                        Name = "Foo Man Choo",
                        Order = 0
                    }
                },
                Files = new List<string> { @"C:\Users\adam_000\Documents\[SBS]_Release_and_Authorization_Form.pdf" }
            };

            try
            {
                var signatureResponse = await helloSign.SignatureRequest.CreateEmbeddedAsync(requestSignature);
                var signatureUrlResponse =
                    await helloSign.Embedded.GetSignUrlAsync(signatureResponse.First().Signatures.First().SignatureId);

                return signatureUrlResponse;
            }

**Comment by jdconley** [comment]
What does the calling code method signature look like? Is the method an "async void" or "async Task"? If the former, it might exit your application, whereas the latter would throw a WebException with the 400 error.

https://msdn.microsoft.com/en-us/magazine/jj991977.aspx

**Comment by MSDP** [comment]
public static async Task<Embedded> RequestSignature()
        {
            var helloSign = new HelloSignClient("##KEY##");
            var requestSignature = new SignatureRequestSendRequest
            {
                Title = "Test",
                Subject = "Subject",
                Message = "Wweeeeeeee",
                TestMode = 1,
                Signers = new List<SignerRequest>
                {
                    new SignerRequest
                    {
                        EmailAddress = "jacob@ms-dp.net",
                        Name = "Foo Man Choo",
                        Order = 0
                    }
                },
                Files = new List<string> { @"C:\Users\adam_000\Documents\[SBS]_Release_and_Authorization_Form.pdf" }
            };

            try
            {
                var signatureResponse = await helloSign.SignatureRequest.CreateEmbeddedAsync(requestSignature);
                var signatureUrlResponse =
                    await helloSign.Embedded.GetSignUrlAsync(signatureResponse.First().Signatures.First().SignatureId);

               
                return signatureUrlResponse;
            }
            catch (Exception ex)
            {
                
            }
            return null;
        }

**Comment by jdconley** [comment]
Cool, and I assume up the call stack this is the same?

**Comment by MSDP** [comment]
Calling Start:        

        static void Main()
        {
            
            var requestSignature = RapidSignService.RequestSignature();
        }

Which is into the previously posted code.

**Comment by jdconley** [comment]
requestSignature in Main is a Task object. You'll need to .Wait() until it completes in Main, which will throw the exception.

**Comment by MSDP** [comment]
There we go, thank you. 

Error: The remote server returned an error: (400) Bad Request. @ HelloSignService.cs - 106:: using (WebResponse response = await webReq.GetResponseAsync())

data = "test_mode=1&file[0]=C%3a%5cUsers%5cadam_000%5cDocuments%5c%5bSBS%5d_Release_and_Authorization_Form.pdf&title=Test&subject=Subject&message=Wweeeeeeee&signers[0][name]=Foo+Man+Choo&signers[0][email_address]=jacob%40ms-dp.net&signers[0][order]=0"

url = "https://api.hellosign.com/v3/signature_request/create_embedded"

endpoint = "/signature_request/create_embedded"

**Comment by MSDP** [comment]
Adam,

Looks like we're receiving the 'file' parameter in the wrong format. The request needs to have Content-Type:multipart/form-data, as when using "curl -F ...". In your case, it looks like the 'file' parameter isn't coming in that way.

Hope this helps,

Stephen Eisenhauer
Software Engineer
HelloSign

**Comment by jdconley** [comment]
I see. It looks like the API to upload a file as part of the embedded request hasn't been implemented. That would have to be added to the library. We use this in conjunction with existing templates that have been uploaded through the HelloSign UI.

**Comment by MSDP** [comment]
Oh I would prefer to use it that way. I'll try it out!
