### ISSUE TITLE
Async Breaks Requests

### ISSUE THREAD

**Issue by MSDP** [realcrowd/hellosign.net#12]
For reasons I cannot explain, the Asynchronous code provided in HelloSignService.cs does not function.

When updating to:

            using (var requestStream = webReq.GetRequestStream())
            {
                requestStream.Write(bytes, 0, bytes.Length);
            }

            using (WebResponse response = webReq.GetResponse())
            {
                using (Stream responseStream = response.GetResponseStream())
                {
                    StreamReader reader = new StreamReader(responseStream);
                    string responseString = reader.ReadToEnd();
                    return JsonConvert.DeserializeObject<T>(responseString);
                }
            }

My application functions flawlessly.

**Comment by jdconley** [comment]
Can you elaborate on "breaks my application"?

Also, if you want to make the calls synchronously, you can just use the HttpClient or WebClient directly in your application. We just wrote a really thin wrapper for us to have strong typing.

Or just use something like RestSharp: http://restsharp.org/

**Comment by MSDP** [comment]
I apologize, it doesn't break my application. 

        var signatureResponse = await         helloSign.SignatureRequest.SendWithTemplateAsync(requestSignature);


will execute however return nothing.

**Comment by jdconley** [comment]
Is it returning null, or an object that isn't populated the way you'd expect?

Maybe set a breakpoint in line 112 of the HelloSignClient:

https://github.com/realcrowd/hellosign.net/blob/d12a840aeefd77677907407848f715fcaff504ee/src/RealCrowd.HelloSign/Services/HelloSignService.cs#L112

Inspect in there... Perhaps the JSON isn't returned in a format we are expecting?

**Comment by MSDP** [comment]
It seems to have to do with Getting the Request Stream via Async. 

Stepping through with a break on:

            webReq.ContentType = "application/x-www-form-urlencoded";

It will hit 

            using (var requestStream = await webReq.GetRequestStreamAsync())

then break again back on webReq (as i'm sending multiple signatures).

**Comment by jdconley** [comment]
Can you show your calling code? There could be a multi-threading issue in there if you have multiple requests running concurrently.

**Comment by MSDP** [comment]
Do you suppose I could email you the code personally? 

I really appreciate your assistance!

**Comment by MSDP** [comment]
@jdconley is the MAN! Silly usage of Asynchronous calls broke the wrapper, now it works perfect! =D
