### ISSUE TITLE
Signature Id Not Return and no error found 

### ISSUE THREAD

**Issue by ashishsws** [realcrowd/hellosign.net#13]
Hi,

i have try to just send the signature request to me and some one my code is running fine no error found but the signature id not generated... and following response come

HelloSign\SignatureRequest Object ( [resource_type:protected] => signature_request [signature_request_id:protected] => [is_complete:protected] => [has_error:protected] => [files_url:protected] => [signing_url:protected] => [details_url:protected] => [cc_email_addresses:protected] => Array ( ) [custom_fields:protected] => Array ( ) [response_data:protected] => [signatures:protected] => HelloSign\SignatureList Object ( [resource_class:protected] => Signature [collection:protected] => Array ( ) [position:protected] => 0 ) [form_fields_per_document:protected] => Array ( ) [signing_redirect_url:protected] => [requesting_redirect_url:protected] => [signers:protected] => HelloSign\SignerList Object ( [resource_class:protected] => Signer [collection:protected] => Array ( [0] => HelloSign\Signer Object ( [name:protected] => Jack [email_address:protected] => jack@gmail.com [order:protected] => [pin:protected] => ) [1] => HelloSign\Signer Object ( [name:protected] => dina [email_address:protected] => dina@gmail.com [order:protected] => [pin:protected] => ) ) [position:protected] => 0 ) [requester_email_address:protected] => [use_text_tags:protected] => [hide_text_tags:protected] => [metadata:protected] => Array ( ) [warnings:protected] => Array ( ) [test_mode:protected] => 1 [title:protected] => Sign New Doc For Our Relationship [subject:protected] => New NDA Sign For Our Business Relationship... [message:protected] => Please sign this NDA and then we can discuss more. Let me know if you have any questions. [file:protected] => Array ( [0] => @nda.docx [1] => @C:\wamp\www\NewHelloSign\library ) [file_url:protected] => Array ( ) ) 

and here is my code... 

<?
require_once('HelloSign\Client.php');

require_once('HelloSign\BaseException.php');
require_once('HelloSign\AbstractObject.php');
require_once('HelloSign\AbstractList.php');
require_once('HelloSign\Signer.php');
require_once('HelloSign\SignerList.php');
require_once('HelloSign\SignatureList.php');
require_once('HelloSign\AbstractResource.php');
require_once('HelloSign\Account.php');
require_once('HelloSign\BaseException.php');
require_once('HelloSign\Error.php');
require_once('HelloSign\AbstractSignatureRequest.php');
require_once('HelloSign\SignatureRequest.php');

include_once **DIR** . '/lib/REST.php';
include_once **DIR** . '/lib/CURL.php';

$client = new HelloSign\Client('mykey');
$request = new HelloSign\SignatureRequest;
$request->enableTestMode();
$request->setTitle('Sign New Doc For Our Relationship');
$request->setSubject('New NDA Sign For Our Business Relationship...');
$request->setMessage('Please sign this NDA and then we can discuss more. Let me know if you have any questions.');
$request->addSigner('jack@gmail.com', 'Jack');
$request->addSigner(new HelloSign\Signer(array(
    'name' => 'dina',
    'email_address' => 'dina@gmail.com'
)));
$request->addFile('nda.docx');
$request->addFile(**DIR**);
$response = $client->sendSignatureRequest($request);
print_r($response);
echo $response->signature_request_id;
 ?>

please suggest me what i will do to get signature id...  thanks..

**Comment by jdconley** [comment]
Hi!

Unfortunately I don't know anything about the PHP SDK. You can find that project over here: https://github.com/HelloFax/hellosign-php-sdk
